server:
  port: 8072

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
         non_contextual_creational: true
         
# SERVICIOS A CONSUMIR
uri:
  #nomina-externa: "http://localhost:8082"
  nomina-externa: "http://rgt-us-nominaexterna:8082"
