server:
  port: 7991

spring:
  datasource:
    url: jdbc:postgresql://10.35.2.65:5431/TEST_GOTALENT
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
         non_contextual_creational: true
